---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lpm.my.domain
  resources:
  - containercheckpointcontents
  - containercheckpoints
  - podcheckpointcontents
  - podcheckpoints
  - podmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lpm.my.domain
  resources:
  - containercheckpointcontents/status
  - containercheckpoints/status
  - podcheckpointcontents/status
  - podcheckpoints/status
  - podmigrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - lpm.my.domain
  resources:
  - containercheckpoints/finalizers
  - podcheckpoints/finalizers
  - podmigrations/finalizers
  verbs:
  - update
