apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: live-pod-migration-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
